version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: B166er.#
      POSTGRES_USER: postgres
      POSTGRES_DB: multitenantDB
      PGDATA: /var/lib/postgressql/data/pgdata
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - djsmdev-network
    volumes:
      - postgres-volumes:/var/lib/postgresql/data
networks:
  djsmdev-network:
volumes:
  postgres-volumes:
